### ISSUE TITLE
Organize coding style

### ISSUE THREAD

**Issue by peter279k** [SenseException/intl-sort#2]
As title, it seems that this package doesn't have the coding style tool.

And we should consider integrating coding style. And the available coding style tools are as follows:

- PHP_CodeSniffer
- PHP-CS-Fixer

And we can also consider using PSR-12 coding style.

**Comment by SenseException** [comment]
Yes, it has none at the moment because CS is kind of a secondary nice to have and not high on my priority list. I consider to use PHP CodeSniffer with the Doctrine coding style in the future.

**Comment by SenseException** [comment]
PHPCS was introduced a few months ago.
